### ISSUE TITLE
Slope Transform- Pull from file for m and b coefficients

### ISSUE THREAD

**Issue by CorinneBassin-SOI** [schmidtocean/openrvdas#5]
The newer slope transform implementation allows for  values to be transformed using mx+b . Our initial use case for this is with the ph calibration which converts the base pH voltage to actual pH using calibration coefficients that are determined prior to each cruise. 
Currently, you would have to update the new values for the calibration in the logger.template and reload that every time the coefficients change. 
It would be better to have this information pulled from a file where the file could be updated by the MT's on board after a calibration takes place and RVDAS updates this information. It would be fine if you still have to rebuild the logger ./build_logger_config.sh
but would be nice not to have to update the template config. 
It could be something similar to how the CruiseID gets updated in the logger at the start of a new cruise

**Comment by KaarelRaeis-SOI** [comment]
Merged new slope correction transform that loads values from yaml in local/soi/slopes/
